version: '3.8'

services:
  mongo:
    image: mongo:8.0.1
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_usr
      MONGO_INITDB_ROOT_PASSWORD: mongo_pwd
    ports:
      - "27017:27017"
